comment/urls.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
'''
@author: zhangshihao
@file: urls.py
@time: 2022/5/8 15:10
'''
from django.urls import path
from . import views

urlpatterns = [
    # 发表评论
    path('post-comment/<int:product_id>/', views.post_comment, name='post_comment'),
    # 处理二级回复
    path('post-comment/<int:product_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

django_fptree_recommend/urls.py
from django.contrib import admin
from django.urls import path, include

from store.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    path('', include('django.contrib.auth.urls')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
]

store/urls.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
'''
@author: zhangshihao
@file: urls.py
@time: 2022/5/5 11:53
'''
from django.urls import path
from store import views

urlpatterns = [
    path('index/', views.index, name='index'),  # 主页
    path('categories/', views.categoryList, name='categories'),  # 大类列表
    path('subcategoryList/<str:cat_name>', views.subcategoryList, name='subcategoryList'),  # 子类列表
    path('product_list/<str:subcat_name>', views.product_list, name='product_list'),  # 商品列表
    path('product/<int:product_id>', views.product, name='product'),  # 商品详情
    path('product/<int:product_id>/<str:username>', views.addToCart, name='addToCart'),  # 添加购物车
    path('remove/<int:product_id>/<str:username>', views.deleteFromCart, name='delete'),  # 删除购物车商品
    path('cart/<str:username>', views.shoppingcart, name='shoppingcart'),  # 购物车页面
    path('orders/<str:username>', views.orders, name='orders'),  # 订单页面
    path('remove_order/<int:order_id>/<str:username>', views.remove_order, name='remove_order'),  # 删除订单
    path('delinfo/<int:cart_id>', views.deliveryInfo, name='checkout'),  # 支付
    path('confirm/<int:cart_id>/<str:username>', views.confirmOrder, name='confirm'),  # 填写订单信息
    path('login/', views.user_login, name='login'),  # 登录
    path('logout/', views.user_logout, name='logout'),  # 登出
    path('register/', views.register, name='register'),  # 注册
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contact/', views.contact, name='contact'),
]

templates/aboutus.html
<title>关于我们</title>
{% extends 'base.html' %}
{% block content %}
    <br>
    <div class="row">
        <div class="col-sm-12">
            <h2 align="center" id="slogan">- About Us -</h2>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link href="{% static 'favicon1.ico' %}" rel="shortcut icon" type="image/x-icon">
    <script src="{% static 'store/js/jquery-3.1.1.min.js' %}"></script>
    {% include 'back_to_top_func.html' %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'store/js/bootstrap.min.js' %}">
    <link rel="stylesheet" href="{% static 'store/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}">
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'store/css/style.css' %}">
    <title>FP Shopping</title>
    <style>
        #index_font{
            font-family: 华文行楷, fangsong;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-6"><a href="{% url 'store:index' %}"><img src="{% static 'store/Kloth.png' %}" alt="图标"></a>
        </div>
        <div class="col-sm-6 text-center text-uppercase" id="slogan">
            <br>
            <br>
            <br>
            <h1>FP Shopping</h1>
            <h3 id="index_font">一站式购物</h3>
        </div>
    </div>
    <hr class="hstyle">
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-center" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto" id="index_font">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'store:index' %}" style="font-size: 20px">主页</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'store:categories' %}" style="font-size: 20px">种类</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <div class="dropdown show">
                            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                               style="font-size: 20px">
                                欢迎，{{ user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'store:shoppingcart' username=user.username %}"
                                   style="font-size: 20px; text-align: center">购物车<i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
                                <a class="dropdown-item" href="{% url 'store:orders' username=user.username %}"
                                   style="font-size: 20px; text-align: center">订单<img
                                        src="{% static 'store/order.jpg' %}" alt=""></a>
                                <a class="dropdown-item" href="{% url 'store:logout' %}" style="font-size: 20px; text-align: center">
                                    登出<i class="fa fa-sign-out" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'store:login' %}?next={{ request.path }}" style="font-size: 20px">登录</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'store:register' %}" style="font-size: 20px">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h6 class="footer-header" style="font-size: 20px;" id="index_font">关于我们</h6>
                    <p><a href="{% url 'store:aboutus' %}" class="footer-text">发现更多关于FP Shopping</a></p>
                </div>
                <div class="col-sm-6">
                    <h6 class="footer-header" style="font-size: 20px;" id="index_font">联系我们</h6>
                    <p><a href="{% url 'store:contact' %}" class="footer-text">您如何联系我们？</a></p>
                </div>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'store/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cart.html
<title>购物车</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">失败</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>购物车中产品数量为0，请检查购物车并重试。</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">成功</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>成功删除商品！</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="location.reload()">关闭</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="product">
        <div class="col-sm-6">
            <h6 id="slogan">产品</h6>
        </div>
        <div class="col-sm-2">
            <h6 id="slogan">单价</h6>
        </div>
        <div class="col-sm-2">
            <h6 id="slogan">数量</h6>
        </div>
        <div class="col-sm-2">
            <h6 id="slogan">总价</h6>
        </div>
    </div>
    <br>
    {% if cart.cart_Products.exists %}
        <form method="post" action="{% url 'store:checkout' cart_id=cart.id %}">
        {% for p in cart.cart_Products.all %}
            <div class="row">
                <div class="col-sm-6">
                    <img src="{{ p.p_url }}" width="250" height="150"
                         alt="https://via.placeholder.com/250x150/FF7F50/FFA500?text=Product">
                    <br>
                    <br>
                    <h6>{{ p.p_name }}</h6>
                </div>
                <div class="col-sm-2">
                    <h6 id="price {{ forloop.counter }}" >{{ p.p_price }}元</h6>
                </div>
                <div class="col-sm-2">
                    <label for="quantity {{ forloop.counter }}"></label>
                    <a class="fa fa-minus" aria-hidden="true" onclick="minus({{ forloop.counter }})"></a>
                    <input type="number" name="quantity" id="quantity {{ forloop.counter }}" value="0" min="0">
                    <a class="fa fa-plus" aria-hidden="true" onclick="plus({{ forloop.counter }})"></a>
                </div>
                <div class="col-sm-1">
                    <h6 id="total {{ forloop.counter }}"></h6>
                </div>
                <div class="col-sm-1">
                    <a class="fa fa-close" href="{% url 'store:delete' product_id=p.id username=user.username %}"
                       onclick="delete_product()"></a>
                </div>
            </div>
            <hr class="separator">
        {% endfor %}
        <div class="row">
            <div class="col-sm-12" align="right">
                <h6 id="slogan">总价:<span id="all"></span></h6>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12" align="right">
                <button name="AddToCart" class="btn btn-primary" id="addtocart" onclick="checkTotal()">支付</button>
            </div>
        </div>
    {% else %}
        <h4 id="slogan" align="center">您的购物车中没有商品，您可以转到
            <a href="{% url 'store:categories' %}">商品页面</a>
            挑选商品</h4>
    {% endif %}
{% csrf_token %}
</form>
    <script src="https://use.fontawesome.com/6039a713fa.js"></script>
    <script>
        var total = 0;

        function plus(a) {
            if (a >= 0) {
                document.getElementById("quantity " + a.toString()).value++;
                var quantity = parseInt(document.getElementById("quantity " + a.toString()).value);
                var price = parseFloat(document.getElementById("price " + a.toString()).innerHTML);
                var sum = price * quantity;
                document.getElementById("total " + a.toString()).innerHTML = sum;
                total = total + price;
                document.getElementById("all").innerHTML = total;
            }
        }

        function minus(a) {
            if (document.getElementById("quantity " + a.toString()).value > 0) {
                document.getElementById("quantity " + a.toString()).value--;
                var quantity = parseInt(document.getElementById("quantity " + a.toString()).value);
                var price = parseFloat(document.getElementById("price " + a.toString()).innerHTML);
                var sum = price * quantity;
                document.getElementById("total " + a.toString()).innerHTML = sum;
                total = total - price;
                document.getElementById("all").innerHTML = total;
            }
        }

        function refresh() {
            location.reload();
        }

        function checkTotal() {
            if (total == 0) {
                $(document).ready(function () {
                    $("#myModal").modal();
                });
            }
        }

        function delete_product() {
            $(document).ready(function () {
                $("#myModal2").modal();
            });
        }
    </script>
{% endblock %}

templates/checkout.html
<title>Checkout</title>
{% extends 'base.html' %}
{% block content %}
<script>
</script>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">成功</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>订单已经处理完成！</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-secondary" href="{% url "store:orders" username=user.username %}">关闭</a>
            </div>
        </div>
    </div>
</div>

    <div class="row">
        <div class="col-sm-8">
            <form id="form1" method="post" action="{% url 'store:confirm' cart_id=cartId username=user.username%}">
                <input type="hidden" value="{% for q in quantity reversed %}{{ q }}{% endfor %}" name="quantity">
                <input type="hidden" value="{{ products }}" name="products">
                <input type="hidden" value="{{ total }}" name="total">
                <div class="form-group">
                    <label for="inputAddress">地址</label>
                    <input type="text" required="required" class="form-control" id="inputAddress" placeholder="1234 Main St"
                           name="address">
                </div>
                <div class="form-group">
                    <label for="inputAddress2">区</label>
                    <input type="text" required="required" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor"
                           name="region">
                </div>
                <div class="form-row">
                    <div class="form-group col-sm-6">
                        <label for="inputCity">城市</label>
                        <input type="text" required="required" class="form-control" id="inputCity" name="city">
                    </div>
                    <div class="form-group col-sm-4">
                        <label for="inputState">省份</label>
                        <select id="inputState" class="form-control" name="province">
                            <option selected>江苏</option>
                            <option>浙江</option>
                            <option>北京</option>
                            <option>上海</option>
                            <option>广东</option>
                            <option>天津</option>
                            <option>河南</option>
                            <option>河北</option>
                            <option>安徽</option>
                            <option>山东</option>
                            <option>江西</option>
                            <option>福建</option>
                            <option>山西</option>
                        </select>
                    </div>
                    <div class="form-group col-sm-2">
                        <label for="inputZip">邮编</label>
                        <input type="text" class="form-control" id="inputZip" name="zipcode">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary" id="addtocart" onclick="confirmOrder()">确认</button>
                {% csrf_token %}
            </form>
        </div>
        <div class="col-sm-4" id="summary">
            <br>
            <h5 id="summary-font">订单信息</h5>
            <hr id="summary">
            <div class="row">
                <div class="col-sm-6">
                    <h6 id="summary-font">商品名称</h6>
                </div>
                <div class="col-sm-3">
                    <h6 id="summary-font">商品数量</h6>
                </div>
                <div class="col-sm-3">
                    <h6 id="summary-font">商品价格</h6>
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                    <div class="col-sm-6">
                        <h6 id="summary-font">{{ product.p_name }}</h6>
                    </div>
                    <div class="col-sm-3">
                        <h6 id="summary-font">{{ quantity.pop }}</h6>
                    </div>
                    <div class="col-sm-3">
                        <h6 id="summary-font">{{ product.p_price }}</h6>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-sm-9">
                    <h6 id="summary-font">订单总价: </h6>
                </div>
                <div class="col-sm-3">
                    <h6 id="summary-font">{{ total }}</h6>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12" align="right">
            <h6 id="summary-font">注意：非常抱歉，目前仅接受现金付款。</h6>
        </div>
    </div>
    <script>
        function confirmOrder() {
            $(document).ready(function () {
                $("#myModal").modal();
            });
        }
    </script>
{% endblock %}

templates/product.html
<title>商品详情页</title>
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    {% load mptt_tags %}
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}">
    <script>
        function atc() {
            $(document).ready(function () {
                $("#myModal").modal();
            });
        }
    </script>
    <br>
    {#    提示框#}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">商品添加</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>商品添加购物车成功</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>

    {#    商品信息#}
    <div class="row">
        <h4 id="slogan">{{ pro.p_name }}</h4>
    </div>
    <hr class="hstyle2">
    <div class="row">
        <div class="col-sm-12" align="center">
            {#            <img src="{% static 'store/productPlaceholder.jpg' %}" width="500" height="500" alt="">#}
            <img src="{{ url }}" width="500" height="500" alt="">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12" align="center">
            <br>
            <h5 id="slogan">价格:&emsp;{{ pro.p_price }}元</h5>
            <div class="card-footer">
                <span>
                    <small class="col align-self-end">
                        浏览: {{ pro.p_total_views }}
                    </small>
                </span>
            </div>
            {% if user.is_authenticated %}
                <a name="AddToCart" class="btn btn-primary" id="addtocart"
                   href="{% url 'store:addToCart' product_id=pro.id username=user.username %}" onclick="atc()">加入购物车</a>
            {% endif %}

        </div>
    </div>
    <hr>
    {% if user.is_authenticated %}
        <div>
            <form action="{% url 'comment:post_comment' pro.id %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            我也要发言：
                        </strong>
                    </label>
                    <div>
                        {{ comment_form.media }}
                        {{ comment_form.content }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary ">发送</button>
            </form>
        </div>
        <br>
    {% else %}
        <br>
        <h5 class="row justify-content-center">请<a href="{% url 'store:login' %}?next={{ request.path }}">登录</a>后回复</h5>
        <br>
    {% endif %}
    <h4>共有{{ comments.count }}条评论</h4>
    <div class="row">
        <!-- 遍历树形结构 -->
        {% recursetree comments %}
            <!-- 给 node 取个别名 comment -->
            {% with comment=node %}
                <div class="{% if comment.reply_to %}
                        offset-1 col-11
                        {% else %}
                        col-12
                        {% endif %}">
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong>
                        {% if comment.reply_to %}
                            <i class="fa fa-arrow-circle-right fa" aria-hidden="true"
                               style="color: cornflowerblue; "></i>
                            <strong style="color: pink">
                                {{ comment.reply_to }}
                            </strong>
                        {% endif %}
                    </p>
                    <div>{{ comment.content|safe }}</div>
                    <div>
                    <span style="color: gray">
                        {{ comment.created|date:"Y-m-d H:i" }}
                    </span>
                        <!-- 加载 modal 的按钮 -->
                        {% if user.is_authenticated %}
                            <button type="button"
                                    class="btn btn-light btn-sm text-muted"
                                    onclick="load_modal({{ pro.id }}, {{ comment.id }})">
                                回复
                            </button>
                        {% else %}
                            <a class="btn btn-light btn-sm text-muted"
                               href="{% url 'store:login' %}">
                                回复
                            </a>
                        {% endif %}
                    </div>
                    <!-- Modal -->
                    <div class="modal fade"
                         id="comment_{{ comment.id }}"
                         tabindex="-1"
                         role="dialog"
                         aria-labelledby="CommentModalCenter"
                         aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                            <div class="modal-content" style="height: 480px">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                </div>
                                <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                            </div>
                        </div>
                    </div>
                    {% if not comment.is_leaf_node %}
                        <div class="children">
                            {{ children }}
                        </div>
                    {% endif %}
                </div>
            {% endwith %}
        {% endrecursetree %}
    </div>
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h6 class="footer-header">为你推荐</h6>
                </div>
                <div class="row">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <div class="row">
                                    {% for r in recItems %}
                                        <div class="col-sm-3" align="center">
                                            <a href="{% url 'store:product' product_id=r.id %}" target="_blank">
                                                <img src="{{ r.p_url }}" alt="First slide"
                                                     style="width: 200px; height: 250px;">
                                            </a>
                                            <h6>{{ r.p_name }}</h6><h6>价格: {{ r.p_price }}元</h6></div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script>
        $(".django-ckeditor-widget").removeAttr('style');
    </script>
    <!-- 新增代码，唤醒二级回复的 modal -->
    <script>
        // 加载 modal
        function load_modal(product_id, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;

            // 加载编辑器
            if ($(modal_body).children().length === 0) {
                let content = '<iframe src="/comment/post-comment/' +
                    product_id +
                    '/' +
                    comment_id +
                    '"' +
                    ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                    comment_id +
                    '"></iframe>';
                $(modal_body).append(content);
            }
            ;
            $(modal_id).modal('show');
        }
    </script>
{% endblock %}

templates/productlist.html
<title>商品列表</title>
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <script>
        function atc() {
            $(document).ready(function () {
                $('#myModal').modal();
            });
        }
    </script>
    <style>
        #product {
            border-style: solid;
            border-color: white white;
            padding-top: 1%;
        }
        #slogan1 {
            text-align: center;
        }
    </style>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">商品添加</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>商品添加购物车成功</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'store:product_list' subcat_name=subcat_name %}?order=p_total_views">
                    最热
                </a>
            </li>
        </ol>
    </nav>
    <div class="row">
        {% for product in products %}
            <div class="col-sm-3" id="product">
                <div class="col-sm-12">
                    <a href="{% url 'store:product' product_id=product.id %}">
                        <img src="{{ product.p_url }}" width="200px" height="250px" class="img-responsive center-block"
                             alt="">
                    </a>
                </div>
                <br>
                <div class="col-sm-12">
                    <h6 align="left" id="slogan1">{{ product.p_name }}</h6>
                </div>
                <div class="col-sm-12">
                    <h6 align="left" id="slogan1">浏览: {{ product.p_total_views }}</h6>
                    <h6 align="left" id="slogan1">价格: {{ product.p_price }}元</h6>
                </div>
                <br>
                {% if user.is_authenticated %}
                    <div class="col-sm-12" style="text-align: center">
                        <a name="AddToCart" class="btn btn-primary" id="addtocart" style=""
                           href="{% url 'store:addToCart' product_id=product.id username=user.username %}"
                           onclick="atc()">加入购物车</a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if products.has_previous %}
                <a href="?page=1&order={{ order }}" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ products.previous_page_number }}&order={{ order }}" class="btn btn-secondary">
                    {{ products.previous_page_number }}
                </a>
            {% endif %}
            <!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ products.number }}
            </span>
            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if products.has_next %}
                <a href="?page={{ products.next_page_number }}&order={{ order }}" class="btn btn-secondary">
                    {{ products.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ products.paginator.num_pages }}&order={{ order }}" class="btn btn-success">
                    {{ products.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
        </div>
    </div>
{% endblock %}